# Generated by Django 5.1 on 2024-10-22 21:21

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=myauth.models.avatar_image_directory_path
            ),
        ),
    ]
