# Generated by Django 5.1 on 2025-01-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0002_alter_article_pub_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
