# Generated by Django 5.0.7 on 2024-08-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0006_order_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "price"]},
        ),
        migrations.AddField(
            model_name="product",
            name="amount",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
