# Generated by Django 5.1 on 2024-10-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_product_options"),
        ("shopapp", "0009_alter_product_created_by"),
    ]

    operations = []
